[package]
name = "iris-ui"
version = "0.1.0"
edition = "2024"

[dependencies]

[[example]]
name = "clock"
path = "../../examples/clock.rs"

[[example]]
name = "lovely_girl"
path = "../../examples/lovely_girl.rs"
